In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('summary_results.csv', sep=',', decimal='.', index_col=0)
df

,instance,status,obj,model time (s),total time (s),gap
0,BAG_10_p2_1_makespan,2,6346.0,7.893,7.939428,0.000000
0,BAG_10_p2_1_deadline,2,5266.0,3.439,3.504273,0.000000
0,BAG_10_p2_2_makespan,2,6071.0,2.874,2.928201,0.000000
0,BAG_10_p2_2_deadline,2,4991.0,3.565,3.615899,0.000000
0,BAG_10_p2_3_makespan,2,6160.0,4.141,4.191972,0.000000
...,...,...,...,...,...,...
0,GNR_20_p2_2_makespan,9,9456.0,3600.534,3603.934477,0.488156
0,GNR_20_p2_2_deadline,9,6606.0,3600.488,3602.988633,0.616107
0,GNR_20_p2_3_makespan,9,8167.0,3600.344,3604.923773,0.365128
0,GNR_20_p2_3_deadline,9,5924.0,3603.743,3605.429496,0.558069
0,GNR_20_p2_4_makespan,9,8659.0,3600.341,3617.616976,0.426955

In [37]:
new_cols = pd.DataFrame({'type': row[0], 'L': row[1], 'p': row[2], 'n': row[3], 'obj': row[4] } for row in df['instance'].str.split('_'))
new_cols

    type   L   p  n       obj
0    BAG  10  p2  1  makespan
1    BAG  10  p2  1  deadline
2    BAG  10  p2  2  makespan
3    BAG  10  p2  2  deadline
4    BAG  10  p2  3  makespan
..   ...  ..  .. ..       ...
282  GNR  20  p2  2  makespan
283  GNR  20  p2  2  deadline
284  GNR  20  p2  3  makespan
285  GNR  20  p2  3  deadline
286  GNR  20  p2  4  makespan

[287 rows x 5 columns]

In [59]:
df1 = pd.concat([df.reset_index(drop=True), new_cols.reset_index(drop=True)], axis='columns')
df1

,instance,status,obj,model time (s),total time (s),gap,type,L,p,n,obj
0,BAG_10_p2_1_makespan,2,6346.0,7.893,7.939428,0.000000,BAG,10,p2,1,makespan
1,BAG_10_p2_1_deadline,2,5266.0,3.439,3.504273,0.000000,BAG,10,p2,1,deadline
2,BAG_10_p2_2_makespan,2,6071.0,2.874,2.928201,0.000000,BAG,10,p2,2,makespan
3,BAG_10_p2_2_deadline,2,4991.0,3.565,3.615899,0.000000,BAG,10,p2,2,deadline
4,BAG_10_p2_3_makespan,2,6160.0,4.141,4.191972,0.000000,BAG,10,p2,3,makespan
...,...,...,...,...,...,...,...,...,...,...,...
282,GNR_20_p2_2_makespan,9,9456.0,3600.534,3603.934477,0.488156,GNR,20,p2,2,makespan
283,GNR_20_p2_2_deadline,9,6606.0,3600.488,3602.988633,0.616107,GNR,20,p2,2,deadline
284,GNR_20_p2_3_makespan,9,8167.0,3600.344,3604.923773,0.365128,GNR,20,p2,3,makespan
285,GNR_20_p2_3_deadline,9,5924.0,3603.743,3605.429496,0.558069,GNR,20,p2,3,deadline
286,GNR_20_p2_4_makespan,9,8659.0,3600.341,3617.616976,0.426955,GNR,20,p2,4,makespan